Repository navgurukul/galileo, pull requests merged in 2020-06, with the labels that each got.

#143 #140
  .gitignore
  README.md
  database.json
  gulpfile.js
  migrations/20200531132552-change-table-cloumn-type.js
  migrations/sqls/20200527054233-change-table-cloumn-type-up.sql
  migrations/sqls/20200531132552-change-table-cloumn-type-down.sql
  migrations/sqls/20200531132552-change-table-cloumn-type-up.sql
  package.json
  sample.env
  src/configurations/index.ts
  src/configurations/sample-config.json
  src/constant.js
  src/controllers/assignments/assignment-controller.ts
  src/controllers/courses/course-controller.ts
  src/controllers/users/user-controller.ts
  src/index.ts
Labels: priority

#145 #39
  migrations/20200602093733-drop-notes-table.js
  migrations/sqls/20200602093733-drop-notes-table-down.sql
  migrations/sqls/20200602093733-drop-notes-table-up.sql
  sample.env
  src/controllers/courses/course-controller.ts
  src/controllers/courses/course-routes.ts
  src/controllers/users/user-controller.ts
  src/controllers/users/user-routes.ts
  src/models/notes-model.ts
Labels: peer-review

#147 #131
  src/controllers/courses/course-controller.ts
  src/controllers/users/user-controller.ts
  src/controllers/users/user-routes.ts
  src/seed-courses.ts
  src/seed-courses/index.ts
  src/seed-courses/validators.ts
Labels: good first issues

#149 Remove unusual things of Cliq
  src/cliq.ts
  src/configurations/index.ts
  src/constant.ts
  src/controllers/assignments/assignment-controller.ts
  src/controllers/courses/course-controller.ts
Labels: good first issues
